package RPG;

public class BattleView extends javax.swing.JPanel {

    /**
     * Creates new form MenuView2
     */
    public BattleView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemsButtonGroup = new javax.swing.ButtonGroup();
        battlePanel = new javax.swing.JPanel();
        battleTitleLabel = new javax.swing.JLabel();
        useItemButton = new javax.swing.JButton();
        battleTextAreaScrollPane = new javax.swing.JScrollPane();
        battleTextArea = new javax.swing.JTextArea();
        attackButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        battlePlayerNameLabel = new javax.swing.JLabel();
        battleHealthLabel = new javax.swing.JLabel();
        escapeButton = new javax.swing.JButton();
        itemPanel = new javax.swing.JPanel();
        itemTitleLabel = new javax.swing.JLabel();
        itemThrowItemButton = new javax.swing.JButton();
        itemExitButton = new javax.swing.JButton();
        itemPlayerNameLabel = new javax.swing.JLabel();
        itemHealthLabel = new javax.swing.JLabel();
        itemUseItemButton = new javax.swing.JButton();
        itemBackButton = new javax.swing.JButton();
        itemItemsScrollPane = new javax.swing.JScrollPane();
        itemSelectItemPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(480, 800));
        setLayout(new java.awt.CardLayout());

        battlePanel.setBackground(new java.awt.Color(102, 102, 102));
        battlePanel.setPreferredSize(new java.awt.Dimension(480, 800));

        battleTitleLabel.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        battleTitleLabel.setText("Into the Depths");

        useItemButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        useItemButton.setText("Use Item");

        battleTextAreaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        battleTextArea.setEditable(false);
        battleTextArea.setBackground(new java.awt.Color(255, 255, 255));
        battleTextArea.setColumns(20);
        battleTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        battleTextArea.setLineWrap(true);
        battleTextArea.setRows(5);
        battleTextArea.setWrapStyleWord(true);
        battleTextArea.setMargin(new java.awt.Insets(5, 10, 2, 6));
        battleTextAreaScrollPane.setViewportView(battleTextArea);

        attackButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        attackButton.setText("Attack");

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        exitButton.setText("Exit to Menu");

        battlePlayerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        battlePlayerNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        battlePlayerNameLabel.setText("Name");
        battlePlayerNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        battleHealthLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        battleHealthLabel.setForeground(new java.awt.Color(255, 255, 255));
        battleHealthLabel.setText("Health: ?/20");

        escapeButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        escapeButton.setText("Escape");

        javax.swing.GroupLayout battlePanelLayout = new javax.swing.GroupLayout(battlePanel);
        battlePanel.setLayout(battlePanelLayout);
        battlePanelLayout.setHorizontalGroup(
            battlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(battleTextAreaScrollPane)
            .addGroup(battlePanelLayout.createSequentialGroup()
                .addGroup(battlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(battlePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(attackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(useItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escapeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(battlePanelLayout.createSequentialGroup()
                        .addGroup(battlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(battlePanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(battleTitleLabel))
                            .addGroup(battlePanelLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addGroup(battlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(battleHealthLabel)
                                    .addComponent(battlePlayerNameLabel))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        battlePanelLayout.setVerticalGroup(
            battlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battlePanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(battleTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(battlePlayerNameLabel)
                .addGap(18, 18, 18)
                .addComponent(battleHealthLabel)
                .addGap(18, 18, 18)
                .addGroup(battlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(useItemButton)
                    .addComponent(exitButton)
                    .addComponent(attackButton)
                    .addComponent(escapeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(battleTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(battlePanel, "card2");

        itemPanel.setBackground(new java.awt.Color(102, 102, 102));
        itemPanel.setPreferredSize(new java.awt.Dimension(480, 800));

        itemTitleLabel.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        itemTitleLabel.setText("Into the Depths");

        itemThrowItemButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        itemThrowItemButton.setText("Throw Item");

        itemExitButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        itemExitButton.setText("Exit to Menu");

        itemPlayerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        itemPlayerNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        itemPlayerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPlayerNameLabel.setText("Name");

        itemHealthLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itemHealthLabel.setForeground(new java.awt.Color(255, 255, 255));
        itemHealthLabel.setText("Health: ?/20");

        itemUseItemButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        itemUseItemButton.setText("Use Item");

        itemBackButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        itemBackButton.setText("Back");

        itemItemsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        itemSelectItemPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout itemSelectItemPanelLayout = new javax.swing.GroupLayout(itemSelectItemPanel);
        itemSelectItemPanel.setLayout(itemSelectItemPanelLayout);
        itemSelectItemPanelLayout.setHorizontalGroup(
            itemSelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        itemSelectItemPanelLayout.setVerticalGroup(
            itemSelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        itemItemsScrollPane.setViewportView(itemSelectItemPanel);

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(itemUseItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemThrowItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itemPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(itemTitleLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(itemHealthLabel)
                    .addComponent(itemPlayerNameLabel))
                .addGap(186, 186, 186))
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(itemTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(itemPlayerNameLabel)
                .addGap(18, 18, 18)
                .addComponent(itemHealthLabel)
                .addGap(18, 18, 18)
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(itemExitButton)
                    .addComponent(itemBackButton)
                    .addComponent(itemThrowItemButton)
                    .addComponent(itemUseItemButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(itemPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackButton;
    private javax.swing.JLabel battleHealthLabel;
    private javax.swing.JPanel battlePanel;
    private javax.swing.JLabel battlePlayerNameLabel;
    private javax.swing.JTextArea battleTextArea;
    private javax.swing.JScrollPane battleTextAreaScrollPane;
    private javax.swing.JLabel battleTitleLabel;
    private javax.swing.JButton escapeButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton itemBackButton;
    private javax.swing.JButton itemExitButton;
    private javax.swing.JLabel itemHealthLabel;
    private javax.swing.JScrollPane itemItemsScrollPane;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JLabel itemPlayerNameLabel;
    private javax.swing.JPanel itemSelectItemPanel;
    private javax.swing.JButton itemThrowItemButton;
    private javax.swing.JLabel itemTitleLabel;
    private javax.swing.JButton itemUseItemButton;
    private javax.swing.ButtonGroup itemsButtonGroup;
    private javax.swing.JButton useItemButton;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel getBattlePanel() {
        return battlePanel;
    }

    public javax.swing.JButton getAttackButton() {
        return attackButton;
    }

    public javax.swing.JLabel getBattleHealthLabel() {
        return battleHealthLabel;
    }

    public javax.swing.JLabel getBattlePlayerNameLabel() {
        return battlePlayerNameLabel;
    }

    public javax.swing.JTextArea getBattleTextArea() {
        return battleTextArea;
    }

    public javax.swing.JButton getUseItemButton() {
        return useItemButton;
    }

    public javax.swing.JButton getEscapeButton() {
        return escapeButton;
    }

    public javax.swing.JButton getExitButton() {
        return exitButton;
    }

    public javax.swing.JButton getItemBackButton() {
        return itemBackButton;
    }

    public javax.swing.JButton getItemExitButton() {
        return itemExitButton;
    }

    public javax.swing.JLabel getItemHealthLabel() {
        return itemHealthLabel;
    }

    public javax.swing.JScrollPane getItemItemsScrollPane() {
        return itemItemsScrollPane;
    }

    public javax.swing.JPanel getItemPanel() {
        return itemPanel;
    }

    public javax.swing.JLabel getItemPlayerNameLabel() {
        return itemPlayerNameLabel;
    }

    public javax.swing.JPanel getItemSelectItemPanel() {
        return itemSelectItemPanel;
    }

    public javax.swing.JButton getItemThrowItemButton() {
        return itemThrowItemButton;
    }

    public javax.swing.JLabel getItemTitleLabel() {
        return itemTitleLabel;
    }

    public javax.swing.JButton getItemUseItemButton() {
        return itemUseItemButton;
    }

    public javax.swing.ButtonGroup getItemsButtonGroup() {
        return itemsButtonGroup;
    }
    
    //Events the GameController must listen for
    public void addController(BattleController controller) {
        attackButton.addActionListener(controller);
        useItemButton.addActionListener(controller);
        escapeButton.addActionListener(controller);
        exitButton.addActionListener(controller);
        
        itemUseItemButton.addActionListener(controller);
        itemThrowItemButton.addActionListener(controller);
        itemBackButton.addActionListener(controller);
        itemExitButton.addActionListener(controller);
    }
}
