package RPG;

import java.util.Observable;
import java.util.Observer;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class GameView extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form MenuView
     */
    public GameView() {
        initComponents();
        
        //Hide all components from other sections of the game menus
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();
        continueForwardButton = new javax.swing.JButton();
        useItemButton = new javax.swing.JButton();
        saveAndExitButton = new javax.swing.JButton();
        healthLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(550, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameTextArea.setEditable(false);
        gameTextArea.setColumns(20);
        gameTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gameTextArea.setLineWrap(true);
        gameTextArea.setRows(5);
        jScrollPane2.setViewportView(gameTextArea);
        gameTextArea.getAccessibleContext().setAccessibleParent(this);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 470, 180));

        continueForwardButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        continueForwardButton.setText("Continue Forward");
        continueForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueForwardButtonActionPerformed(evt);
            }
        });
        add(continueForwardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, 40));

        useItemButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        useItemButton.setText("Use Item");
        useItemButton.setEnabled(false);
        useItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useItemButtonActionPerformed(evt);
            }
        });
        add(useItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 540, -1, 40));

        saveAndExitButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        saveAndExitButton.setText("Save & Exit to Menu");
        add(saveAndExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, 40));

        healthLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        healthLabel.setForeground(new java.awt.Color(255, 255, 255));
        healthLabel.setText("Health:");
        add(healthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void continueForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueForwardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueForwardButtonActionPerformed

    private void useItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useItemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueForwardButton;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveAndExitButton;
    private javax.swing.JButton useItemButton;
    // End of variables declaration//GEN-END:variables
    
    //Returns the continue forward button
    public JButton getContinueForwardButton() {
        return this.continueForwardButton;
    }

    //Returns the game text area
    public JTextArea getGameTextArea() {
        return this.gameTextArea;
    }
    
    //Returns the health label
    public JLabel getHealthLabel() {
        return this.healthLabel;
    }
    
    //Returns the save and exit button
    public JButton getSaveAndExitButton() {
        return this.saveAndExitButton;
    }

    //Return the use item button
    public JButton getUseItemButton() {
        return this.useItemButton;
    }
    
    @Override
    public void update(Observable o, Object arg) {}
    
    //Register the menu controller to the view
    public void addController(GameController controller) {
        this.continueForwardButton.addActionListener(controller);
        this.saveAndExitButton.addActionListener(controller);
        this.useItemButton.addActionListener(controller);
    }
}