package RPG;

import javax.swing.ButtonGroup;

public class GameView extends javax.swing.JPanel {

    /**
     * Creates new form MenuView2
     */
    public GameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemsButtonGroup = new javax.swing.ButtonGroup();
        gamePanel = new javax.swing.JPanel();
        gameTitleLabel = new javax.swing.JLabel();
        gameUseItemButton = new javax.swing.JButton();
        gameTextAreaScrollPane = new javax.swing.JScrollPane();
        gameTextArea = new javax.swing.JTextArea();
        continueFowardButton = new javax.swing.JButton();
        saveAndExitButton = new javax.swing.JButton();
        gamePlayerNameLabel = new javax.swing.JLabel();
        gameHealthLabel = new javax.swing.JLabel();
        itemPanel = new javax.swing.JPanel();
        itemTitleLabel = new javax.swing.JLabel();
        itemThrowItemButton = new javax.swing.JButton();
        itemExitButton = new javax.swing.JButton();
        itemPlayerNameLabel = new javax.swing.JLabel();
        itemHealthLabel = new javax.swing.JLabel();
        itemUseItemButton = new javax.swing.JButton();
        itemBackButton = new javax.swing.JButton();
        itemItemsScrollPane = new javax.swing.JScrollPane();
        itemSelectItemPanel = new javax.swing.JPanel();
        battlePanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(480, 800));
        setLayout(new java.awt.CardLayout());

        gamePanel.setBackground(new java.awt.Color(102, 102, 102));
        gamePanel.setPreferredSize(new java.awt.Dimension(480, 800));

        gameTitleLabel.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        gameTitleLabel.setText("Into the Depths");

        gameUseItemButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        gameUseItemButton.setText("Use Item");

        gameTextAreaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        gameTextArea.setEditable(false);
        gameTextArea.setBackground(new java.awt.Color(255, 255, 255));
        gameTextArea.setColumns(20);
        gameTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gameTextArea.setLineWrap(true);
        gameTextArea.setRows(5);
        gameTextArea.setWrapStyleWord(true);
        gameTextArea.setMargin(new java.awt.Insets(5, 10, 2, 6));
        gameTextAreaScrollPane.setViewportView(gameTextArea);

        continueFowardButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        continueFowardButton.setText("Continue Forward");

        saveAndExitButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        saveAndExitButton.setText("Save & Exit");

        gamePlayerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        gamePlayerNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        gamePlayerNameLabel.setText("Name");
        gamePlayerNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        gameHealthLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gameHealthLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameHealthLabel.setText("Health: ?/20");

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameTextAreaScrollPane)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(gameTitleLabel))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(continueFowardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameUseItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveAndExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(gameHealthLabel)
                            .addComponent(gamePlayerNameLabel))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(gameTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(gamePlayerNameLabel)
                .addGap(18, 18, 18)
                .addComponent(gameHealthLabel)
                .addGap(18, 18, 18)
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(gameUseItemButton)
                    .addComponent(saveAndExitButton)
                    .addComponent(continueFowardButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(gamePanel, "card2");

        itemPanel.setBackground(new java.awt.Color(102, 102, 102));
        itemPanel.setPreferredSize(new java.awt.Dimension(480, 800));

        itemTitleLabel.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        itemTitleLabel.setText("Into the Depths");

        itemThrowItemButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        itemThrowItemButton.setText("Throw Item");

        itemExitButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        itemExitButton.setText("Save & Exit");

        itemPlayerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        itemPlayerNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        itemPlayerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPlayerNameLabel.setText("Name");

        itemHealthLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itemHealthLabel.setForeground(new java.awt.Color(255, 255, 255));
        itemHealthLabel.setText("Health: ?/20");

        itemUseItemButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        itemUseItemButton.setText("Use Item");

        itemBackButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        itemBackButton.setText("Back");

        itemItemsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        itemSelectItemPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout itemSelectItemPanelLayout = new javax.swing.GroupLayout(itemSelectItemPanel);
        itemSelectItemPanel.setLayout(itemSelectItemPanelLayout);
        itemSelectItemPanelLayout.setHorizontalGroup(
            itemSelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        itemSelectItemPanelLayout.setVerticalGroup(
            itemSelectItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        itemItemsScrollPane.setViewportView(itemSelectItemPanel);

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(itemUseItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemThrowItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itemPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(itemTitleLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(itemHealthLabel)
                    .addComponent(itemPlayerNameLabel))
                .addGap(186, 186, 186))
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(itemTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(itemPlayerNameLabel)
                .addGap(18, 18, 18)
                .addComponent(itemHealthLabel)
                .addGap(18, 18, 18)
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(itemExitButton)
                    .addComponent(itemBackButton)
                    .addComponent(itemThrowItemButton)
                    .addComponent(itemUseItemButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(itemPanel, "card2");

        javax.swing.GroupLayout battlePanelLayout = new javax.swing.GroupLayout(battlePanel);
        battlePanel.setLayout(battlePanelLayout);
        battlePanelLayout.setHorizontalGroup(
            battlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        battlePanelLayout.setVerticalGroup(
            battlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        add(battlePanel, "card4");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel battlePanel;
    private javax.swing.JButton continueFowardButton;
    private javax.swing.JLabel gameHealthLabel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel gamePlayerNameLabel;
    private javax.swing.JTextArea gameTextArea;
    private javax.swing.JScrollPane gameTextAreaScrollPane;
    private javax.swing.JLabel gameTitleLabel;
    private javax.swing.JButton gameUseItemButton;
    private javax.swing.JButton itemBackButton;
    private javax.swing.JButton itemExitButton;
    private javax.swing.JLabel itemHealthLabel;
    private javax.swing.JScrollPane itemItemsScrollPane;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JLabel itemPlayerNameLabel;
    private javax.swing.JPanel itemSelectItemPanel;
    private javax.swing.JButton itemThrowItemButton;
    private javax.swing.JLabel itemTitleLabel;
    private javax.swing.JButton itemUseItemButton;
    private javax.swing.ButtonGroup itemsButtonGroup;
    private javax.swing.JButton saveAndExitButton;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel getBattlePanel() {
        return battlePanel;
    }

    public javax.swing.JButton getContinueFowardButton() {
        return continueFowardButton;
    }

    public javax.swing.JLabel getGameHealthLabel() {
        return gameHealthLabel;
    }

    public javax.swing.JPanel getGamePanel() {
        return gamePanel;
    }

    public javax.swing.JLabel getGamePlayerNameLabel() {
        return gamePlayerNameLabel;
    }

    public javax.swing.JTextArea getGameTextArea() {
        return gameTextArea;
    }

    public javax.swing.JButton getGameUseItemButton() {
        return gameUseItemButton;
    }

    public javax.swing.JButton getItemBackButton() {
        return itemBackButton;
    }

    public javax.swing.JButton getItemExitButton() {
        return itemExitButton;
    }

    public javax.swing.JLabel getItemHealthLabel() {
        return itemHealthLabel;
    }

    public javax.swing.JScrollPane getItemItemsScrollPane() {
        return itemItemsScrollPane;
    }
    
    public javax.swing.ButtonGroup getItemsButtonGroup() {
        return itemsButtonGroup;
    }

    public javax.swing.JPanel getItemPanel() {
        return itemPanel;
    }

    public javax.swing.JLabel getItemPlayerNameLabel() {
        return itemPlayerNameLabel;
    }

    public javax.swing.JPanel getItemSelectItemPanel() {
        return itemSelectItemPanel;
    }

    public javax.swing.JButton getItemThrowItemButton() {
        return itemThrowItemButton;
    }

    public javax.swing.JButton getItemUseItemButton() {
        return itemUseItemButton;
    }

    public javax.swing.JButton getSaveAndExitButton() {
        return saveAndExitButton;
    }
    
    public void setBattlePanel(BattleView battleView) {
        battlePanel = battleView;
    }
    
    //Events the GameController must listen for
    public void addController(GameController controller) {
        this.getContinueFowardButton().addActionListener(controller);
        this.getGameUseItemButton().addActionListener(controller);
        this.getSaveAndExitButton().addActionListener(controller);
        
        this.getItemBackButton().addActionListener(controller);
        this.getItemUseItemButton().addActionListener(controller);
        this.getItemExitButton().addActionListener(controller);
        this.getItemThrowItemButton().addActionListener(controller);
    }
}
