package RPG;

import java.util.Observable;
import java.util.Observer;

public class MenuView extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newGameButton = new javax.swing.JButton();
        loadGameButton = new javax.swing.JButton();
        viewScoresButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        bestScoreLabel = new javax.swing.JLabel();
        bestScoreHeaderLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setNextFocusableComponent(newGameButton);
        setPreferredSize(new java.awt.Dimension(550, 500));

        newGameButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newGameButton.setText("New Game");

        loadGameButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loadGameButton.setText("Load Game");

        viewScoresButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewScoresButton.setText("View Scores");

        quitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quitButton.setText("Quit");

        titleLabel.setFont(new java.awt.Font("Candara Light", 1, 48)); // NOI18N
        titleLabel.setText("Into the Depths");

        bestScoreLabel.setText("No scores yet");
        bestScoreLabel.setEnabled(false);

        bestScoreHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bestScoreHeaderLabel.setText("Best Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadGameButton)
                    .addComponent(viewScoresButton)
                    .addComponent(quitButton)
                    .addComponent(titleLabel)
                    .addComponent(bestScoreLabel)
                    .addComponent(bestScoreHeaderLabel))
                .addGap(50, 50, 50))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {loadGameButton, newGameButton, quitButton, viewScoresButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bestScoreHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bestScoreLabel)
                .addGap(46, 46, 46)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadGameButton)
                .addGap(18, 18, 18)
                .addComponent(viewScoresButton)
                .addGap(18, 18, 18)
                .addComponent(quitButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {loadGameButton, newGameButton, quitButton, viewScoresButton});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestScoreHeaderLabel;
    private javax.swing.JLabel bestScoreLabel;
    private javax.swing.JButton loadGameButton;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewScoresButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    //Register the menu controller to the view
    public void addController(MenuController controller) {
        newGameButton.addActionListener(controller);
        loadGameButton.addActionListener(controller);
        viewScoresButton.addActionListener(controller);
        quitButton.addActionListener(controller);
    }
}
